### ISSUE TITLE
Organizations are not imported by importing their server and being in the code.

### ISSUE THREAD

**Issue by ticdenis** [disc/terraform-provider-pritunl#16]
Given the following example after importing and running the plan we see that you have not attached the organizations to their server.

```terraform
# ...

resource "pritunl_organization" "this" {
  name = "example"
}

resource "pritunl_server" "this" {
  # ...
  organization_ids  = [
    pritunl_organization.this.id
  ]
}
```

Output after planning:

```text
Terraform will perform the following actions:

  # pritunl_server.this will be updated in-place
  ~ resource "pritunl_server" "this" {
      #...
      ~ organization_ids   = [
          + "example-organization-id",
        ]
    }

```

**Comment by disc** [comment]
Hey @ticdenis thas a good point, looks like a bug.
I will look into it this week

**Comment by disc** [comment]
@ticdenis Can you describe the imports order?
Did you import the organization and the server?

**Comment by ticdenis** [comment]
> @ticdenis Can you describe the imports order?
> Did you import the organization and the server?
Yes, first the org and after the server.

**Comment by disc** [comment]
@ticdenis Could you show me the tfstate after import the organization and then after import the server.
It should contain both resources.
So far I can't reproduce the issue

**Comment by disc** [comment]
Can't reproduce
