### ISSUE TITLE
Any plans to support links?

### ISSUE THREAD

**Issue by oblogic7** [disc/terraform-provider-pritunl#27]
I'm trying to use pritunl to manage multiple site-to-site configurations and would like to configure the links via Terraform. I don't see any resources to manage links, locations or routes to support this use case.  Am I missing something or is this not currently implemented in the provider?

**Comment by disc** [comment]
Hey @oblogic7. For now supported only these features of the **Pritunl** (those cover my needs for now)
- Servers (with routes support)
- Users
- Organizations

If you're talking about this Link feature (https://docs.pritunl.com/docs/link-configuration) - you can create a feature request and it can be implemented in future.
