### ISSUE TITLE
any plans for host related resources?

### ISSUE THREAD

**Issue by dlethin** [disc/terraform-provider-pritunl#3]
Great plugin -- thanks for starting and sharing this.  I've only briefly tried it out with a new test server and it looked like it was doing the right thing. Would make a nice change from the manual work we're doing today as the number of servers we support grows.

Are there any plans for adding support for hosts in the near future? I could potentially try to take a crack at it with a PR, but would hold off if it's currently planned and/or in the works.

Any thoughts on how best to implement it?   I was assuming given you can't add hosts directly through the UI, that implementing a host data resource, searchable by id might be the way to go, along with a host_settings resource.
Then there's the question of how to handle host server attachments -- whether to embed them directly in the server resource, similar to what you did with organization attachments, or create a host_server_attachment resource which takes as input a host_id and server_id.

Cheers.

**Comment by dlethin** [comment]
I made a first pass at a draft PR #4

**Comment by disc** [comment]
Hey @dlethin, I'm not familiar with multiple hosts yet I will look into it this/next week.
I'm going to try them and they decide how to implement it as a datasource or as a regular resource.
