### ISSUE TITLE
Route not supporting NET GATEWAY

### ISSUE THREAD

**Issue by LePhanFF** [disc/terraform-provider-pritunl#37]
Existing code
https://github.com/disc/terraform-provider-pritunl/blob/d1abdac633c05a41f30579c04044c877b20e5c58/internal/pritunl/route.go#L15C2-L15C12

has NetGateway listed as one of the route, however, function ConvertMapToRoute does not have conditional logic to support setting route as net_gateway.

Could we do a PR to add support for net_gateway?

**Comment by disc** [comment]
Hello @LePhanFF, you can deferentially make a fix and support this functionality. Your contribution will be helpful for all the users of the provider.

**Comment by LePhanFF** [comment]
@disc  please review and approve https://github.com/disc/terraform-provider-pritunl/pull/38

**Comment by LePhanFF** [comment]
Hello, 

I was able to make modifications in PR : https://github.com/disc/terraform-provider-pritunl/pull/39

Also modified the unit test to show that the attribute it set properly for net_gateway attribute to true on route.

I was also able to capture the admin screenshot with its attribute set.

**Comment by disc** [comment]
Solved in #39
